export const apiPaths = {
    getProjects: 'project/getProjects',
    getProject: '/projects/:id',
    createProject: 'project/createProject',
    updateProject: '/projects/:id',
    createTask: 'task/createTask',
    getTasks: 'task/getTasks',
    updateTask: 'task/updateTask',
    deleteTask: 'task/deleteTask',
    getIssues: 'issue/getIssues',
    createIssue: 'issue/createIssue',
    getDiscussions: 'discussion/getDiscussions',
    createDiscussion: 'discussion/createDiscussion',
    updateDiscussion: 'discussion/updateDiscussion',
    deleteDiscussion: 'discussion/deleteDiscussion',
    getComments: 'comment/getComments',
    addComment: 'comment/addComment',
    authenticate: 'user/authenticate',
    getUsers: 'user/getUsers',
    getActiveUsers: 'user/getActiveUsers',
    getNotifications: 'notification/getNotifications',
    sendMessage: 'chat/sendMessage',
    getMessages: 'chat/getMessages',
}